version: 2.1

references:
  x-workdir: &work-dir
    working_directory: ~/source

  x-save-workspace: &persist-step
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  x-attach: &attach-step
    attach_workspace:
      at: .

jobs:
  install-dependencies:
    <<: *work-dir
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - *persist-step

  lint:
    <<: *work-dir
    docker:
      - image: node
    steps:
      - *attach-step
      - run:
          name: lint
          command: npm run lint

  node-8:
    docker:
      - image: circleci/node:8
    steps:
      - *attach-step
      - run:
          name: Test
          command: npm test

  node-10:
    docker:
      - image: circleci/node:10
    steps:
      - *attach-step
      - run:
          name: Test
          command: npm test

  node-12:
    docker:
      - image: circleci/node:12
    steps:
      - *attach-step
      - run:
          name: Test with coverage
          command: npm run test-coverage
      - run:
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash) -F unit -s coverage/lcov.info

  integration-test:
    docker:
      - image: circleci/node:12
    steps:
      - *attach-step
      - run:
          name: Build
          command: npm run build
      - run:
          name: Integration test
          command: npm run integration-test

workflows:
  version: 2
  sinon-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - node-8:
          requires:
            - install-dependencies
      - node-10:
          requires:
            - install-dependencies
      - node-12:
          requires:
            - install-dependencies
      - integration-test:
          requires:
            - install-dependencies
            - lint
            - node-8
            - node-10
            - node-12
